// <auto-generated />
using System;
using Backend_poulina_future_jobs.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend_poulina_future_jobs.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend_poulina_future_jobs.Models.AppUserCompetence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompetenceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NiveauPossede")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompetenceId");

                    b.HasIndex("AppUserId", "CompetenceId")
                        .IsUnique();

                    b.ToTable("AppUserCompetences", (string)null);
                });

            modelBuilder.Entity("Backend_poulina_future_jobs.Models.Candidature", b =>
                {
                    b.Property<Guid>("IdCandidature")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateSoumission")
                        .HasColumnType("datetime2");

                    b.Property<string>("MessageMotivation")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("OffreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdCandidature");

                    b.HasIndex("OffreId");

                    b.HasIndex("AppUserId", "OffreId")
                        .IsUnique();

                    b.ToTable("Candidatures");
                });

            modelBuilder.Entity("Backend_poulina_future_jobs.Models.Certificat", b =>
                {
                    b.Property<Guid>("IdCertificat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateObtention")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("ExperienceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Organisme")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("UrlDocument")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdCertificat");

                    b.HasIndex("ExperienceId");

                    b.ToTable("Certificats");
                });

            modelBuilder.Entity("Backend_poulina_future_jobs.Models.Competence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dateAjout")
                        .HasColumnType("datetime2");

                    b.Property<bool>("estSoftSkill")
                        .HasColumnType("bit");

                    b.Property<bool>("estTechnique")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Competences", (string)null);
                });

            modelBuilder.Entity("Backend_poulina_future_jobs.Models.Departement", b =>
                {
                    b.Property<Guid>("IdDepartement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdFiliale")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdDepartement");

                    b.HasIndex("IdFiliale");

                    b.ToTable("Departements", (string)null);
                });

            modelBuilder.Entity("Backend_poulina_future_jobs.Models.Diplome", b =>
                {
                    b.Property<Guid>("IdDiplome")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Domaine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Niveau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomDiplome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDiplome");

                    b.ToTable("Diplomes");
                });

            modelBuilder.Entity("Backend_poulina_future_jobs.Models.Experience", b =>
                {
                    b.Property<Guid>("IdExperience")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompetenceAcquise")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("DateDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("NomEntreprise")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Poste")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdExperience");

                    b.HasIndex("AppUserId");

                    b.ToTable("Experiences");
                });

            modelBuilder.Entity("Backend_poulina_future_jobs.Models.Filiale", b =>
                {
                    b.Property<Guid>("IdFiliale")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Fax")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("IdRecruteur")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiteWeb")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdFiliale");

                    b.HasIndex("IdRecruteur");

                    b.ToTable("Filiales");
                });

            modelBuilder.Entity("Backend_poulina_future_jobs.Models.OffreCompetences", b =>
                {
                    b.Property<Guid>("IdOffreEmploi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdCompetence")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NiveauRequis")
                        .HasColumnType("int");

                    b.HasKey("IdOffreEmploi", "IdCompetence");

                    b.HasIndex("IdCompetence");

                    b.ToTable("OffreCompetences", (string)null);
                });

            modelBuilder.Entity("Backend_poulina_future_jobs.Models.OffreEmploi", b =>
                {
                    b.Property<Guid>("IdOffreEmploi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Avantages")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("DateExpiration")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatePublication")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdDepartement")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdFiliale")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdRecruteur")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ModeTravail")
                        .HasColumnType("int");

                    b.Property<string>("NiveauExperienceRequis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SalaireMax")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SalaireMin")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Specialite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.Property<int>("TypeContrat")
                        .HasColumnType("int");

                    b.Property<bool>("estActif")
                        .HasColumnType("bit");

                    b.HasKey("IdOffreEmploi");

                    b.HasIndex("IdDepartement");

                    b.HasIndex("IdFiliale");

                    b.HasIndex("IdRecruteur");

                    b.ToTable("OffresEmploi", (string)null);
                });

            modelBuilder.Entity("Backend_poulina_future_jobs.Models.OffreLangue", b =>
                {
                    b.Property<Guid>("IdOffreLangue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdOffreEmploi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Langue")
                        .HasColumnType("int");

                    b.Property<string>("NiveauRequis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdOffreLangue");

                    b.HasIndex("IdOffreEmploi");

                    b.ToTable("OffreLangues");
                });

            modelBuilder.Entity("Backend_poulina_future_jobs.Models.OffreMission", b =>
                {
                    b.Property<Guid>("IdOffreMission")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DescriptionMission")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdOffreEmploi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Priorite")
                        .HasColumnType("int");

                    b.HasKey("IdOffreMission");

                    b.HasIndex("IdOffreEmploi");

                    b.ToTable("OffreMissions");
                });

            modelBuilder.Entity("Backend_poulina_future_jobs.Models.Poste", b =>
                {
                    b.Property<Guid>("IdPoste")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExperienceSouhaitee")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdOffreEmploi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NiveauHierarchique")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NombrePostes")
                        .HasColumnType("int");

                    b.Property<string>("TitrePoste")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPoste");

                    b.HasIndex("IdOffreEmploi");

                    b.ToTable("Postes");
                });

            modelBuilder.Entity("Backend_poulina_future_jobs.Models.Question", b =>
                {
                    b.Property<Guid>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Ordre")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("TempsRecommande")
                        .HasColumnType("int");

                    b.Property<string>("Texte")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("QuestionId");

                    b.HasIndex("QuizId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("Backend_poulina_future_jobs.Models.Quiz", b =>
                {
                    b.Property<Guid>("QuizId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Duree")
                        .HasColumnType("int");

                    b.Property<bool>("EstActif")
                        .HasColumnType("bit");

                    b.Property<Guid?>("OffreEmploiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ScoreMinimum")
                        .HasColumnType("int");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("QuizId");

                    b.HasIndex("AppUserId");

                    b.HasIndex("OffreEmploiId");

                    b.ToTable("Quizzes");
                });

            modelBuilder.Entity("Backend_poulina_future_jobs.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Backend_poulina_future_jobs.Models.Reponse", b =>
                {
                    b.Property<Guid>("ReponseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EstCorrecte")
                        .HasColumnType("bit");

                    b.Property<string>("Explication")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Ordre")
                        .HasColumnType("int");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Texte")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ReponseId");

                    b.HasIndex("QuestionId");

                    b.ToTable("Reponses");
                });

            modelBuilder.Entity("Backend_poulina_future_jobs.Models.ReponseUtilisateur", b =>
                {
                    b.Property<Guid>("ReponseUtilisateurId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EstCorrecte")
                        .HasColumnType("bit");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ReponseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("TempsReponse")
                        .HasColumnType("int");

                    b.Property<Guid>("TentativeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TexteReponse")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("ReponseUtilisateurId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("ReponseId");

                    b.HasIndex("TentativeId");

                    b.ToTable("ReponsesUtilisateur");
                });

            modelBuilder.Entity("Backend_poulina_future_jobs.Models.ResultatQuiz", b =>
                {
                    b.Property<Guid>("ResultatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Commentaire")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("DateResultat")
                        .HasColumnType("datetime2");

                    b.Property<int>("NombreQuestions")
                        .HasColumnType("int");

                    b.Property<int>("QuestionsCorrectes")
                        .HasColumnType("int");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Reussi")
                        .HasColumnType("bit");

                    b.Property<double>("Score")
                        .HasColumnType("float");

                    b.Property<int>("TempsTotal")
                        .HasColumnType("int");

                    b.Property<Guid>("TentativeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ResultatId");

                    b.HasIndex("TentativeId")
                        .IsUnique();

                    b.ToTable("ResultatsQuiz");
                });

            modelBuilder.Entity("Backend_poulina_future_jobs.Models.TentativeQuiz", b =>
                {
                    b.Property<Guid>("TentativeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AppUserId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Score")
                        .HasColumnType("float");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.HasKey("TentativeId");

                    b.HasIndex("AppUserId");

                    b.HasIndex("AppUserId1");

                    b.HasIndex("QuizId");

                    b.ToTable("TentativesQuiz");
                });

            modelBuilder.Entity("DiplomeOffreEmploi", b =>
                {
                    b.Property<Guid>("DiplomesRequisIdDiplome")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OffresEmploiIdOffreEmploi")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DiplomesRequisIdDiplome", "OffresEmploiIdOffreEmploi");

                    b.HasIndex("OffresEmploiIdOffreEmploi");

                    b.ToTable("OffreEmploiDiplomes", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator().HasValue("IdentityUser<Guid>");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Backend_poulina_future_jobs.Models.AppUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser<System.Guid>");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateNaissance")
                        .HasColumnType("datetime2");

                    b.Property<string>("Diplome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Entreprise")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid?>("IdFiliale")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NiveauEtude")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Pays")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Poste")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Universite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("github")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("linkedIn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("portfolio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("specialite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("IdFiliale");

                    b.HasDiscriminator().HasValue("AppUser");
                });

            modelBuilder.Entity("Backend_poulina_future_jobs.Models.AppUserCompetence", b =>
                {
                    b.HasOne("Backend_poulina_future_jobs.Models.AppUser", "AppUser")
                        .WithMany("AppUserCompetences")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend_poulina_future_jobs.Models.Competence", "Competence")
                        .WithMany("AppUserCompetences")
                        .HasForeignKey("CompetenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Competence");
                });

            modelBuilder.Entity("Backend_poulina_future_jobs.Models.Candidature", b =>
                {
                    b.HasOne("Backend_poulina_future_jobs.Models.AppUser", "AppUser")
                        .WithMany("Candidatures")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend_poulina_future_jobs.Models.OffreEmploi", "Offre")
                        .WithMany("Candidatures")
                        .HasForeignKey("OffreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Offre");
                });

            modelBuilder.Entity("Backend_poulina_future_jobs.Models.Certificat", b =>
                {
                    b.HasOne("Backend_poulina_future_jobs.Models.Experience", "Experience")
                        .WithMany("Certificats")
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Experience");
                });

            modelBuilder.Entity("Backend_poulina_future_jobs.Models.Departement", b =>
                {
                    b.HasOne("Backend_poulina_future_jobs.Models.Filiale", "Filiale")
                        .WithMany("Departements")
                        .HasForeignKey("IdFiliale")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Filiale");
                });

            modelBuilder.Entity("Backend_poulina_future_jobs.Models.Experience", b =>
                {
                    b.HasOne("Backend_poulina_future_jobs.Models.AppUser", "AppUser")
                        .WithMany("Experiences")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("Backend_poulina_future_jobs.Models.Filiale", b =>
                {
                    b.HasOne("Backend_poulina_future_jobs.Models.AppUser", "Recruteur")
                        .WithMany()
                        .HasForeignKey("IdRecruteur");

                    b.Navigation("Recruteur");
                });

            modelBuilder.Entity("Backend_poulina_future_jobs.Models.OffreCompetences", b =>
                {
                    b.HasOne("Backend_poulina_future_jobs.Models.Competence", "Competence")
                        .WithMany("OffreCompetences")
                        .HasForeignKey("IdCompetence")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend_poulina_future_jobs.Models.OffreEmploi", "OffreEmploi")
                        .WithMany("OffreCompetences")
                        .HasForeignKey("IdOffreEmploi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competence");

                    b.Navigation("OffreEmploi");
                });

            modelBuilder.Entity("Backend_poulina_future_jobs.Models.OffreEmploi", b =>
                {
                    b.HasOne("Backend_poulina_future_jobs.Models.Departement", "Departement")
                        .WithMany("OffresEmploi")
                        .HasForeignKey("IdDepartement")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend_poulina_future_jobs.Models.Filiale", "Filiale")
                        .WithMany("OffresEmploi")
                        .HasForeignKey("IdFiliale")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend_poulina_future_jobs.Models.AppUser", "Recruteur")
                        .WithMany("OffresEmploi")
                        .HasForeignKey("IdRecruteur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departement");

                    b.Navigation("Filiale");

                    b.Navigation("Recruteur");
                });

            modelBuilder.Entity("Backend_poulina_future_jobs.Models.OffreLangue", b =>
                {
                    b.HasOne("Backend_poulina_future_jobs.Models.OffreEmploi", "OffreEmploi")
                        .WithMany("OffreLangues")
                        .HasForeignKey("IdOffreEmploi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OffreEmploi");
                });

            modelBuilder.Entity("Backend_poulina_future_jobs.Models.OffreMission", b =>
                {
                    b.HasOne("Backend_poulina_future_jobs.Models.OffreEmploi", "OffreEmploi")
                        .WithMany("OffreMissions")
                        .HasForeignKey("IdOffreEmploi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OffreEmploi");
                });

            modelBuilder.Entity("Backend_poulina_future_jobs.Models.Poste", b =>
                {
                    b.HasOne("Backend_poulina_future_jobs.Models.OffreEmploi", "OffreEmploi")
                        .WithMany("Postes")
                        .HasForeignKey("IdOffreEmploi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OffreEmploi");
                });

            modelBuilder.Entity("Backend_poulina_future_jobs.Models.Question", b =>
                {
                    b.HasOne("Backend_poulina_future_jobs.Models.Quiz", "Quiz")
                        .WithMany("Questions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("Backend_poulina_future_jobs.Models.Quiz", b =>
                {
                    b.HasOne("Backend_poulina_future_jobs.Models.AppUser", null)
                        .WithMany("QuizzesTentés")
                        .HasForeignKey("AppUserId");

                    b.HasOne("Backend_poulina_future_jobs.Models.OffreEmploi", "OffreEmploi")
                        .WithMany("Quizzes")
                        .HasForeignKey("OffreEmploiId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("OffreEmploi");
                });

            modelBuilder.Entity("Backend_poulina_future_jobs.Models.RefreshToken", b =>
                {
                    b.HasOne("Backend_poulina_future_jobs.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend_poulina_future_jobs.Models.Reponse", b =>
                {
                    b.HasOne("Backend_poulina_future_jobs.Models.Question", "Question")
                        .WithMany("Reponses")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Backend_poulina_future_jobs.Models.ReponseUtilisateur", b =>
                {
                    b.HasOne("Backend_poulina_future_jobs.Models.Question", "Question")
                        .WithMany("ReponsesUtilisateur")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend_poulina_future_jobs.Models.Reponse", "Reponse")
                        .WithMany("ReponsesUtilisateur")
                        .HasForeignKey("ReponseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Backend_poulina_future_jobs.Models.TentativeQuiz", "Tentative")
                        .WithMany("ReponsesUtilisateur")
                        .HasForeignKey("TentativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("Reponse");

                    b.Navigation("Tentative");
                });

            modelBuilder.Entity("Backend_poulina_future_jobs.Models.ResultatQuiz", b =>
                {
                    b.HasOne("Backend_poulina_future_jobs.Models.TentativeQuiz", "Tentative")
                        .WithOne("Resultat")
                        .HasForeignKey("Backend_poulina_future_jobs.Models.ResultatQuiz", "TentativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tentative");
                });

            modelBuilder.Entity("Backend_poulina_future_jobs.Models.TentativeQuiz", b =>
                {
                    b.HasOne("Backend_poulina_future_jobs.Models.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend_poulina_future_jobs.Models.AppUser", null)
                        .WithMany("Tentatives")
                        .HasForeignKey("AppUserId1");

                    b.HasOne("Backend_poulina_future_jobs.Models.Quiz", "Quiz")
                        .WithMany("Tentatives")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("DiplomeOffreEmploi", b =>
                {
                    b.HasOne("Backend_poulina_future_jobs.Models.Diplome", null)
                        .WithMany()
                        .HasForeignKey("DiplomesRequisIdDiplome")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend_poulina_future_jobs.Models.OffreEmploi", null)
                        .WithMany()
                        .HasForeignKey("OffresEmploiIdOffreEmploi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend_poulina_future_jobs.Models.AppUser", null)
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend_poulina_future_jobs.Models.AppUser", b =>
                {
                    b.HasOne("Backend_poulina_future_jobs.Models.Filiale", "Filiale")
                        .WithMany("Users")
                        .HasForeignKey("IdFiliale")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Filiale");
                });

            modelBuilder.Entity("Backend_poulina_future_jobs.Models.Competence", b =>
                {
                    b.Navigation("AppUserCompetences");

                    b.Navigation("OffreCompetences");
                });

            modelBuilder.Entity("Backend_poulina_future_jobs.Models.Departement", b =>
                {
                    b.Navigation("OffresEmploi");
                });

            modelBuilder.Entity("Backend_poulina_future_jobs.Models.Experience", b =>
                {
                    b.Navigation("Certificats");
                });

            modelBuilder.Entity("Backend_poulina_future_jobs.Models.Filiale", b =>
                {
                    b.Navigation("Departements");

                    b.Navigation("OffresEmploi");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Backend_poulina_future_jobs.Models.OffreEmploi", b =>
                {
                    b.Navigation("Candidatures");

                    b.Navigation("OffreCompetences");

                    b.Navigation("OffreLangues");

                    b.Navigation("OffreMissions");

                    b.Navigation("Postes");

                    b.Navigation("Quizzes");
                });

            modelBuilder.Entity("Backend_poulina_future_jobs.Models.Question", b =>
                {
                    b.Navigation("Reponses");

                    b.Navigation("ReponsesUtilisateur");
                });

            modelBuilder.Entity("Backend_poulina_future_jobs.Models.Quiz", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("Tentatives");
                });

            modelBuilder.Entity("Backend_poulina_future_jobs.Models.Reponse", b =>
                {
                    b.Navigation("ReponsesUtilisateur");
                });

            modelBuilder.Entity("Backend_poulina_future_jobs.Models.TentativeQuiz", b =>
                {
                    b.Navigation("ReponsesUtilisateur");

                    b.Navigation("Resultat")
                        .IsRequired();
                });

            modelBuilder.Entity("Backend_poulina_future_jobs.Models.AppUser", b =>
                {
                    b.Navigation("AppUserCompetences");

                    b.Navigation("Candidatures");

                    b.Navigation("Experiences");

                    b.Navigation("OffresEmploi");

                    b.Navigation("QuizzesTentés");

                    b.Navigation("Tentatives");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
